-- MySQL Script generated by MySQL Workbench
-- 08/18/17 20:06:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema public_transport
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema public_transport
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `public_transport` DEFAULT CHARACTER SET utf8 ;
USE `public_transport` ;

-- -----------------------------------------------------
-- Table `public_transport`.`line`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `public_transport`.`line` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `short_name` VARCHAR(255) NULL,
  `name` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `deleted` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `deleted` (`deleted` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `public_transport`.`trip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `public_transport`.`trip` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `line_id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `color` VARCHAR(255) NULL,
  `direction` TINYINT NULL,
  `duration` VARCHAR(255) NULL,
  `deleted` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `deleted` (`deleted` ASC),
  INDEX `fk_trip_line1_idx` (`line_id` ASC),
  CONSTRAINT `fk_trip_line1`
    FOREIGN KEY (`line_id`)
    REFERENCES `public_transport`.`line` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `public_transport`.`stop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `public_transport`.`stop` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `latitude` DECIMAL(10,8) NULL,
  `longitude` DECIMAL(11,8) NULL,
  `deleted` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `deleted` (`deleted` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `public_transport`.`arrival`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `public_transport`.`arrival` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `trip_id` INT NOT NULL,
  `stop_id` INT NOT NULL,
  `arrival` VARCHAR(255) NULL,
  `deleted` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `deleted` (`deleted` ASC),
  INDEX `fk_time_trip1_idx` (`trip_id` ASC),
  INDEX `fk_time_stop1_idx` (`stop_id` ASC),
  CONSTRAINT `fk_time_trip1`
    FOREIGN KEY (`trip_id`)
    REFERENCES `public_transport`.`trip` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_time_stop1`
    FOREIGN KEY (`stop_id`)
    REFERENCES `public_transport`.`stop` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
